In [18]:
import polars as pl
from rise_analysis.io import load_comments_json
from rise_analysis.duplicates import assign_duplicate_clusters

In [6]:
COMMENTS_PATH = "../local-data/ED-2025-OPE-0944_2026-03-30.json"

In [7]:
comments = load_comments_json(COMMENTS_PATH)

In [24]:
dupes_df = assign_duplicate_clusters(comments, similarity_threshold = 0.85)

In [25]:
dupes_df.head(10)

shape: (10, 6)
┌─────────────────┬────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ comment_id      ┆ cluster_id ┆ text_clean     ┆ is_trivial_aft ┆ removed_attach ┆ removed_docket │
│ ---             ┆ ---        ┆ ---            ┆ er_clean       ┆ _boilerplate   ┆ _boilerplate   │
│ str             ┆ i64        ┆ str            ┆ ---            ┆ ---            ┆ ---            │
│                 ┆            ┆                ┆ bool           ┆ bool           ┆ bool           │
╞═════════════════╪════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ ED-2025-OPE-094 ┆ 0          ┆ To the         ┆ false          ┆ false          ┆ false          │
│ 4-17445         ┆            ┆ Department of  ┆                ┆                ┆                │
│                 ┆            ┆ Education…     ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 1          ┆ Include        ┆ false          ┆ false          ┆ false          │
│ 4-17446         ┆            ┆ education      ┆                ┆                ┆                │
│                 ┆            ┆ students in …  ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 2          ┆ I am the       ┆ false          ┆ false          ┆ false          │
│ 4-17447         ┆            ┆ patient of an  ┆                ┆                ┆                │
│                 ┆            ┆ ND who …       ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 3          ┆ See comments   ┆ false          ┆ false          ┆ false          │
│ 4-17448         ┆            ┆ in uploaded    ┆                ┆                ┆                │
│                 ┆            ┆ file.…         ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 4          ┆ Dear Education ┆ false          ┆ false          ┆ false          │
│ 4-17449         ┆            ┆ Secretary      ┆                ┆                ┆                │
│                 ┆            ┆ McMah…         ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 5          ┆ Secretary of   ┆ false          ┆ false          ┆ false          │
│ 4-17450         ┆            ┆ Education      ┆                ┆                ┆                │
│                 ┆            ┆ Linda M…       ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 6          ┆ Dear Education ┆ false          ┆ false          ┆ false          │
│ 4-17451         ┆            ┆ Secretary      ┆                ┆                ┆                │
│                 ┆            ┆ McMah…         ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 7          ┆ Dear Members   ┆ false          ┆ false          ┆ false          │
│ 4-17452         ┆            ┆ of the U.S.    ┆                ┆                ┆                │
│                 ┆            ┆ Depar…         ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 8          ┆ I am a patient ┆ false          ┆ false          ┆ false          │
│ 4-17453         ┆            ┆ of a licensed  ┆                ┆                ┆                │
│                 ┆            ┆ n…             ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 9          ┆ Dear Ms. Tamy  ┆ false          ┆ false          ┆ false          │
│ 4-17454         ┆            ┆ Abernathy, My  ┆                ┆                ┆                │
│                 ┆            ┆ na…            ┆                ┆                ┆                │
└─────────────────┴────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [27]:
len(dupes_df)

17730

In [26]:
dupes_df.select(pl.col("cluster_id")).max()

shape: (1, 1)
┌────────────┐
│ cluster_id │
│ ---        │
│ i64        │
╞════════════╡
│ 17057      │
└────────────┘

In [42]:
dupes_df.group_by("cluster_id").agg(pl.col("comment_id").count()).sort("comment_id", descending=True).head(10)

shape: (10, 2)
┌────────────┬────────────┐
│ cluster_id ┆ comment_id │
│ ---        ┆ ---        │
│ i64        ┆ u32        │
╞════════════╪════════════╡
│ 12         ┆ 436        │
│ 419        ┆ 48         │
│ 190        ┆ 21         │
│ 283        ┆ 11         │
│ 8615       ┆ 9          │
│ 3015       ┆ 9          │
│ 3207       ┆ 7          │
│ 3255       ┆ 7          │
│ 8055       ┆ 7          │
│ 325        ┆ 6          │
└────────────┴────────────┘

In [48]:
dupes_df.filter(pl.col("cluster_id") == 419).head()

shape: (5, 6)
┌─────────────────┬────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ comment_id      ┆ cluster_id ┆ text_clean     ┆ is_trivial_aft ┆ removed_attach ┆ removed_docket │
│ ---             ┆ ---        ┆ ---            ┆ er_clean       ┆ _boilerplate   ┆ _boilerplate   │
│ str             ┆ i64        ┆ str            ┆ ---            ┆ ---            ┆ ---            │
│                 ┆            ┆                ┆ bool           ┆ bool           ┆ bool           │
╞═════════════════╪════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ ED-2025-OPE-094 ┆ 419        ┆ Comment on ED- ┆ false          ┆ false          ┆ false          │
│ 4-15896         ┆            ┆ 2025-OPE-0944  ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 419        ┆ Comment on ED- ┆ false          ┆ false          ┆ false          │
│ 4-16087         ┆            ┆ 2025-OPE-0944  ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 419        ┆ Comment on ED- ┆ false          ┆ false          ┆ false          │
│ 4-17220         ┆            ┆ 2025-OPE-0944  ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 419        ┆ Comment on ED- ┆ false          ┆ false          ┆ false          │
│ 4-15602         ┆            ┆ 2025-OPE-0944  ┆                ┆                ┆                │
│ ED-2025-OPE-094 ┆ 419        ┆ Comment on ED- ┆ false          ┆ false          ┆ false          │
│ 4-15776         ┆            ┆ 2025-OPE-0944  ┆                ┆                ┆                │
└─────────────────┴────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [49]:
dupes_df.filter(pl.col("cluster_id") == 190).head()

shape: (5, 6)
┌──────────────────┬────────────┬────────────┬─────────────────┬─────────────────┬─────────────────┐
│ comment_id       ┆ cluster_id ┆ text_clean ┆ is_trivial_afte ┆ removed_attach_ ┆ removed_docket_ │
│ ---              ┆ ---        ┆ ---        ┆ r_clean         ┆ boilerplate     ┆ boilerplate     │
│ str              ┆ i64        ┆ str        ┆ ---             ┆ ---             ┆ ---             │
│                  ┆            ┆            ┆ bool            ┆ bool            ┆ bool            │
╞══════════════════╪════════════╪════════════╪═════════════════╪═════════════════╪═════════════════╡
│ ED-2025-OPE-0944 ┆ 190        ┆ file       ┆ true            ┆ true            ┆ false           │
│ -17649           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 190        ┆ file       ┆ true            ┆ true            ┆ false           │
│ -17743           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 190        ┆ file.      ┆ true            ┆ true            ┆ false           │
│ -16454           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 190        ┆ file.      ┆ true            ┆ true            ┆ false           │
│ -16688           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 190        ┆ file       ┆ true            ┆ true            ┆ false           │
│ -16742           ┆            ┆            ┆                 ┆                 ┆                 │
└──────────────────┴────────────┴────────────┴─────────────────┴─────────────────┴─────────────────┘

In [50]:
dupes_df.filter(pl.col("cluster_id") == 283).head()

shape: (5, 6)
┌──────────────────┬────────────┬────────────┬─────────────────┬─────────────────┬─────────────────┐
│ comment_id       ┆ cluster_id ┆ text_clean ┆ is_trivial_afte ┆ removed_attach_ ┆ removed_docket_ │
│ ---              ┆ ---        ┆ ---        ┆ r_clean         ┆ boilerplate     ┆ boilerplate     │
│ str              ┆ i64        ┆ str        ┆ ---             ┆ ---             ┆ ---             │
│                  ┆            ┆            ┆ bool            ┆ bool            ┆ bool            │
╞══════════════════╪════════════╪════════════╪═════════════════╪═════════════════╪═════════════════╡
│ ED-2025-OPE-0944 ┆ 283        ┆ please     ┆ true            ┆ true            ┆ false           │
│ -17746           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 283        ┆ Please     ┆ true            ┆ true            ┆ false           │
│ -16304           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 283        ┆ Please     ┆ true            ┆ true            ┆ false           │
│ -16861           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 283        ┆ Please     ┆ true            ┆ true            ┆ false           │
│ -17087           ┆            ┆            ┆                 ┆                 ┆                 │
│ ED-2025-OPE-0944 ┆ 283        ┆ Please     ┆ true            ┆ true            ┆ false           │
│ -14847           ┆            ┆            ┆                 ┆                 ┆                 │
└──────────────────┴────────────┴────────────┴─────────────────┴─────────────────┴─────────────────┘